spring:
  # 데이터 소스 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/myppt
    username: sa
    password:
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 5
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
      data-source-properties:
        rewriteBatchedStatements: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1MB
      max-file-size: 1MB
      max-request-size: 10MB


  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        default_batch_fetch_size: ${chunkSize:100}
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
        format_sql: true

  # Security OAuth
  security:
    oauth2.client:
      registration:
        google:
          clientId: '901578003779-44j5ogfuvr12m4e7trf7r1mevj2tsj9r.apps.googleusercontent.com'
          clientSecret: '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'
          scope:
            - email
            - profile

logging:
  level:
    org.hibernate.SQL: debug

file:
  dir: /Users/ryu/ToyProject/MYPPTFE/assets


# jwt secret key 설정
jwt:
  secret: '8sknjlO3NPTBqo319DHLNqsQAfRJEdKsETOds'

cors:
  allowed-origins: 'http://localhost:3000'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600


# 토큰 관련 secret Key 및 RedirectUri 설정
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect